from __future__ import annotations

from collections.abc import Sequence

import numpy as np
import numpy.typing as npt

def stereo_to_mono(samples: npt.ArrayLike) -> npt.NDArray[np.float32]: ...
def interleaved_to_mono(samples: npt.ArrayLike, channels: int) -> npt.NDArray[np.float32]: ...
def rms(samples: npt.ArrayLike) -> float: ...
def peak_normalize(samples: npt.ArrayLike, target_peak: float = ...) -> npt.NDArray[np.float32]: ...
def frame_signal(
    samples: npt.ArrayLike, frame_size: int, hop_size: int, pad_end: bool = ...
) -> Sequence[Sequence[float]]: ...
